project_id = "hmjclidojxubpvgsiegu"

[functions.approve-onboarding]
verify_jwt = false

[functions.reject-onboarding]
verify_jwt = false

[functions.validate-setup-token]
verify_jwt = false

[functions.complete-setup]
verify_jwt = false

[functions.validate-access-token]
verify_jwt = false

[functions.generate-access-token]
verify_jwt = false

[functions.finalize-onboarding]
verify_jwt = false

[functions.send-beta-invitation]
verify_jwt = false
